// File: ANIMATION_MODE.h
#if !defined(_ANIMATION_MODE_H)
#define _ANIMATION_MODE_H
enum ANIMATION_MODE
{
	ANIMATION_MODE_ONCE = 1,
	ANIMATION_MODE_OSCILLATE,
	ANIMATION_MODE_LOOP
};
#endif //_ANIMATION_MODE_H
// Author: Stanley Taveras