// File: MOUSE_BUTTONS.h
// Author: Stanley Taveras
// Created: 3/4/2010
// Modified: 3/4/2010

#pragma once

//MOUSE_LEFT = DIMOFS_BUTTON0,
//MOUSE_RIGHT = DIMOFS_BUTTON1,
//MOUSE_MIDDLE = DIMOFS_BUTTON2,
//MOUSE_3 = DIMOFS_BUTTON3,
//MOUSE_4 = DIMOFS_BUTTON4,
//MOUSE_5 = DIMOFS_BUTTON5,
//MOUSE_6 = DIMOFS_BUTTON6,
//MOUSE_7 = DIMOFS_BUTTON7,

enum MOUSE_BUTTONS
{
   MOUSE_LEFT,
   MOUSE_RIGHT,
   MOUSE_MIDDLE,
   MOUSE_3,
   MOUSE_4,
   MOUSE_5,
   MOUSE_6,
   MOUSE_7,
};